# Generated by Django 5.0.6 on 2024-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
