# Generated by Django 5.0.6 on 2024-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_person_first_name_alter_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=5),
        ),
    ]
