# Generated by Django 5.0.6 on 2024-07-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_person_first_name_alter_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
