# Generated by Django 5.0.6 on 2024-07-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_person_password_remove_person_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
