# Generated by Django 5.0.6 on 2024-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_library_profile_book_author_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='f', max_length=1),
        ),
    ]
