# Generated by Django 5.0.6 on 2024-06-30 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_personal_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loan_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='release_data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
